# Generated by Django 5.2 on 2025-06-24 18:07

from django.db import migrations, models
import uuid  # import uuid to generate default uuid

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
