# Generated by Django 5.2 on 2025-06-07 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSentencePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(blank=True, max_length=50, null=True)),
                ('source_text', models.TextField()),
                ('source_word_start_index', models.IntegerField()),
                ('source_word_end_index', models.IntegerField()),
                ('translated_text', models.TextField()),
                ('translated_word_start_index', models.IntegerField()),
                ('translated_word_end_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_pairs', to='words.translation')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_pairs', to='words.word')),
            ],
        ),
    ]
