# Generated by Django 5.2 on 2025-06-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_examplesentencepair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplesentencepair',
            name='part_of_speech',
        ),
    ]
