# Generated by Django 5.2 on 2025-06-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_remove_examplesentencepair_part_of_speech'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
