# Generated by Django 5.2 on 2025-06-18 17:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_translation_popularity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertranslation',
            unique_together={('user', 'word', 'translation')},
        ),
    ]
